export const initialState = {
    user: null,
    allUsers: null,
    allSongs: null,
    allAlbums: null,
    artists: null,
    artistFilter: null,
    languageFilter: null,
    albumFilter: null,
    filterTerm: "all",
    song: 0,
    isSongPlaying: false,
    searchTerm: "",
    songByArtist: null,
};